# Generated by Django 4.2 on 2023-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_availabel',
            field=models.BooleanField(default=True),
        ),
    ]
