# Generated by Django 4.2 on 2023-06-23 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
