# Generated by Django 4.2 on 2023-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_commentandrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentandrating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
