# Generated by Django 4.2 on 2023-06-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_commentandrating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentandrating',
            name='ip',
        ),
    ]
