# Generated by Django 4.2 on 2023-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_commentandrating_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentandrating',
            name='review',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
