# Generated by Django 4.2 on 2023-06-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profil_picture',
            field=models.ImageField(blank=True, upload_to='photos/userprofile/'),
        ),
    ]
