# Generated by Django 3.2 on 2023-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_profil_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesFromUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=700)),
            ],
        ),
    ]
