# Generated by Django 3.2 on 2023-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_messagesfromus'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesfromus',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
