# Generated by Django 4.2 on 2023-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_surname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
