# Generated by Django 4.2 on 2023-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment_payer_name_payment_payer_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
