# Generated by Django 4.2 on 2023-06-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_payment_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
    ]
